### ISSUE TITLE
mod_vcard_riak cant search empty fields

### ISSUE THREAD

**Issue by andrewvmail** [esl/MongooseIM#1831]
MongooseIM version: master & 2.2.2
Installed from: (source)
Erlang/OTP version: (19)

I was experimenting with riak today and found that the vcard search function is not working.
First I used official riak docker + mongoose docker combo. Then i build both from source. Then i tried older version of riakkv. All gives similar error messages like below. I made sure that riak is prepped with the riak scripts in tools folder. made sure riak search = on too

mongoose log
```
2018-04-30 02:37:10.420 [error] <0.566.0>@mod_vcard_riak:do_search:89 Error while search vCard, index=vcard, query=_yz_rb:vcard_localhost AND vCard.ORG.ORGUNIT: AND vCard.ORG.ORGNAME: AND vCard.EMAIL.USERID: AND vCard.ADR.LOCALITY: AND vCard.ADR.CTRY: AND vCard.BDAY: AND vCard.NICKNAME: AND vCard.N.FAMILY: AND vCard.N.MIDDLE: AND vCard.N.GIVEN: AND vCard.FN: AND _yz_rk:user, error={error,<<"Query unsuccessful check the logs.">>} 
2018-04-30 02:37:10.420 [debug] <0.566.0>@ejabberd_router:route:120 route
        from {jid,<<>>,<<"vjud.localhost">>,<<>>,<<>>,<<"vjud.localhost">>,<<>>}
        to {jid,<<"user">>,<<"localhost">>,<<"Mac-Pro-2">>,<<"user">>,<<"localhost">>,<<"Mac-Pro-2">>}
        packet #{attrs => [{<<"id">>,<<"aad3a">>},{<<"type">>,<<"result">>}],element => {xmlel,<<"iq">>,[{<<"id">>,<<"aad3a">>},{<<"type">>,<<"result">>}],[{xmlel,<<"query">>,[{<<"xmlns">>,<<"jabber:iq:search">>}],[{xmlel,<<"x">>,[{<<"xmlns">>,<<"jabber:x:data">>},{<<"type">>,<<"result">>}],[{xmlel,<<"title">>,[],[{xmlcdata,[<<"Search Results for ">>,<<"vjud.localhost">>]}]},{xmlel,<<"reported">>,[],[{xmlel,<<"field">>,[{<<"type">>,<<"jid-single">>},{<<"label">>,<<"Jabber ID">>},{<<"var">>,<<"jid">>}],[]},{xmlel,<<"field">>,[{<<"type">>,<<"text-single">>},{<<"label">>,<<"Full Name">>},{<<"var">>,<<"fn">>}],[]},{xmlel,<<"field">>,[{<<"type">>,<<"text-single">>},{<<"label">>,<<"Name">>},{<<"var">>,<<"first">>}],[]},{xmlel,<<"field">>,[{<<"type">>,<<"text-single">>},{<<"label">>,<<"Middle Name">>},{<<"var">>,<<"middle">>}],[]},{xmlel,<<"field">>,[{<<"type">>,<<"text-single">>},{<<"label">>,<<"Family Name">>},{<<"var">>,<<"last">>}],[]},{xmlel,<<"field">>,[{<<"type">>,<<"text-single">>},{<<"label">>,<<"Nickname">>},{<<"var">>,<<"nick">>}],[]},{xmlel,<<"field">>,[{<<"type">>,<<"text-single">>},{<<"label">>,<<"Birthday">>},{<<"var">>,<<"bday">>}],[]},{xmlel,<<"field">>,[{<<"type">>,<<"text-single">>},{<<"label">>,<<"Country">>},{<<"var">>,<<"ctry">>}],[]},{xmlel,<<"field">>,[{<<"type">>,<<"text-single">>},{<<"label">>,<<"City">>},{<<"var">>,<<"locality">>}],[]},{xmlel,<<"field">>,[{<<"type">>,<<"text-single">>},{<<"label">>,<<"Email">>},{<<"var">>,<<"email">>}],[]},{xmlel,<<"field">>,[{<<"type">>,<<"text-single">>},{<<"label">>,<<"Organization Name">>},{<<"var">>,<<"orgname">>}],[]},{xmlel,<<"field">>,[{<<"type">>,<<"text-single">>},{<<"label">>,<<"Organization Unit">>},{<<"var">>,<<"orgunit">>}],[]}]}]},{xmlel,<<"set">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/rsm">>}],[{xmlel,<<"count">>,[],[{xmlcdata,<<"0">>}]}]}]}]},from => <<"vjud.localhost">>,from_jid => {jid,<<>>,<<"vjud.localhost">>,<<>>,<<>>,<<"vjud.localhost">>,<<>>},mongoose_acc => true,name => <<"iq">>,ref => #Ref<0.1514699973.1335623681.201202>,timestamp => {1525,81030,420268},to => <<"user@localhost/Mac-Pro-2">>,to_jid => {jid,<<"user">>,<<"localhost">>,<<"Mac-Pro-2">>,<<"user">>,<<"localhost">>,<<"Mac-Pro-2">>},type => <<"result">>}
```

riak log
```
Caused by: org.apache.solr.search.SyntaxError: Cannot parse '_yz_rb:vcard_localhost AND vCard.ORG.ORGUNIT: AND vCard.ORG.ORGNAME: AND vCard.EMAIL.USERID: AND vCard.ADR.LOCALITY: AND vCard.ADR.CTRY: AND vCard.BDAY: AND vCard.NICKNAME: AND vCard.N.FAMILY: AND vCard.N.MIDDLE: AND vCard.N.GIVEN: AND vCard.FN: AND _yz_rk:user': Encountered " <AND> "AND "" at line 1, column 46.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <LPARAMS> ...
    <NUMBER> ...
    
	at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:156)
	at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:50)
	at org.apache.solr.search.QParser.getQuery(QParser.java:141)
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:143)
	... 31 more
Caused by: org.apache.solr.parser.ParseException: Encountered " <AND> "AND "" at line 1, column 46.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <LPARAMS> ...
    <NUMBER> ...
    
	at org.apache.solr.parser.QueryParser.generateParseException(QueryParser.java:649)
	at org.apache.solr.parser.QueryParser.jj_consume_token(QueryParser.java:531)
	at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:216)
	at org.apache.solr.parser.QueryParser.Query(QueryParser.java:139)
	at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:96)
	at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:152)
	... 34 more


==> log/error.log <==
2018-04-30 02:37:10.419 [error] <0.3555.0>@yz_pb_search:maybe_process:107 {solr_error,{400,"http://localhost:8093/internal_solr/vcard/select",<<"{\"error\":{\"msg\":\"org.apache.solr.search.SyntaxError: Cannot parse '_yz_rb:vcard_localhost AND vCard.ORG.ORGUNIT: AND vCard.ORG.ORGNAME: AND vCard.EMAIL.USERID: AND vCard.ADR.LOCALITY: AND vCard.ADR.CTRY: AND vCard.BDAY: AND vCard.NICKNAME: AND vCard.N.FAMILY: AND vCard.N.MIDDLE: AND vCard.N.GIVEN: AND vCard.FN: AND _yz_rk:user': Encountered \\\" <AND> \\\"AND \\\"\\\" at line 1, column 46.\\nWas expecting one of:\\n    <BAREOPER> ...\\n    \\\"(\\\" ...\\n    \\\"*\\\" ...\\n    <QUOTED> ...\\n    <TERM> ...\\n    <PREFIXTERM> ...\\n    <WILDTERM> ...\\n    <REGEXPTERM> ...\\n    \\\"[\\\" ...\\n    \\\"{\\\" ...\\n    <LPARAMS> ...\\n    <NUMBER> ...\\n    \",\"code\":400}}\n">>}} [{yz_solr,search,3,[{file,"src/yz_solr.erl"},{line,277}]},{yz_pb_search,maybe_process,3,[{file,"src/yz_pb_search.erl"},{line,78}]},{riak_api_pb_server,process_message,4,[{file,"src/riak_api_pb_server.erl"},{line,388}]},{riak_api_pb_server,connected,2,[{file,"src/riak_api_pb_server.erl"},{line,226}]},{riak_api_pb_server,decode_buffer,2,[{file,"src/riak_api_pb_server.erl"},{line,364}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,505}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]

==> log/console.log <==
2018-04-30 02:37:10.419 [error] <0.3555.0>@yz_pb_search:maybe_process:107 {solr_error,{400,"http://localhost:8093/internal_solr/vcard/select",<<"{\"error\":{\"msg\":\"org.apache.solr.search.SyntaxError: Cannot parse '_yz_rb:vcard_localhost AND vCard.ORG.ORGUNIT: AND vCard.ORG.ORGNAME: AND vCard.EMAIL.USERID: AND vCard.ADR.LOCALITY: AND vCard.ADR.CTRY: AND vCard.BDAY: AND vCard.NICKNAME: AND vCard.N.FAMILY: AND vCard.N.MIDDLE: AND vCard.N.GIVEN: AND vCard.FN: AND _yz_rk:user': Encountered \\\" <AND> \\\"AND \\\"\\\" at line 1, column 46.\\nWas expecting one of:\\n    <BAREOPER> ...\\n    \\\"(\\\" ...\\n    \\\"*\\\" ...\\n    <QUOTED> ...\\n    <TERM> ...\\n    <PREFIXTERM> ...\\n    <WILDTERM> ...\\n    <REGEXPTERM> ...\\n    \\\"[\\\" ...\\n    \\\"{\\\" ...\\n    <LPARAMS> ...\\n    <NUMBER> ...\\n    \",\"code\":400}}\n">>}} [{yz_solr,search,3,[{file,"src/yz_solr.erl"},{line,277}]},{yz_pb_search,maybe_process,3,[{file,"src/yz_pb_search.erl"},{line,78}]},{riak_api_pb_server,process_message,4,[{file,"src/riak_api_pb_server.erl"},{line,388}]},{riak_api_pb_server,connected,2,[{file,"src/riak_api_pb_server.erl"},{line,226}]},{riak_api_pb_server,decode_buffer,2,[{file,"src/riak_api_pb_server.erl"},{line,364}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,505}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]
```

**Comment by andrewvmail** [comment]
Okay i figured it out. mod_vcard_riak slightly behaves differently than the mnesia equavalent. it doesnt like empty values. I'm using adium and psi for testing and they default to sending empty values on all the empty fields.

So this works
```
<iq type="set" to="vjud.localhost" id="ab25a">
<query xmlns="jabber:iq:search">
<x xmlns="jabber:x:data" type="submit">
<field type="text-single" var="user">
<value>user</value>
</field>
</x>
</query>
</iq>
```

And this doesnt
```
<iq type="set" to="vjud.localhost" id="ab26a">
<query xmlns="jabber:iq:search">
<x xmlns="jabber:x:data" type="submit">
<field type="text-single" var="user">
<value>user</value>
</field>
<field type="text-single" var="fn">
<value></value>
</field>
<field type="text-single" var="first">
<value></value>
</field>
<field type="text-single" var="middle">
<value></value>
</field>
<field type="text-single" var="last">
<value></value>
</field>
<field type="text-single" var="nick">
<value></value>
</field>
<field type="text-single" var="bday">
<value></value>
</field>
<field type="text-single" var="ctry">
<value></value>
</field>
<field type="text-single" var="locality">
<value></value>
</field>
<field type="text-single" var="email">
<value></value>
</field>
<field type="text-single" var="orgname">
<value></value>
</field>
<field type="text-single" var="orgunit">
<value></value>
</field>
</x>
</query>
</iq>
```

**Comment by aleklisi** [comment]
@andrewvmail Is the issue solved?

**Comment by andrewvmail** [comment]
@andrewvmail yeah not an issue for me anymore
