### ISSUE TITLE
Unable to retrieve offline messages in MUCLight

### ISSUE THREAD

**Issue by theanhoo** [esl/MongooseIM#2240]
MongooseIM version: 3.2.0
Installed from: source
Erlang/OTP version: 20
Client: Ignite Realtime Smack 4.3.2

I am able to retrieve offline messages for private chats but not able to for MUCLight.

```
  { mod_mam_meta, [
    { backend, rdbms },
    { async_writer, true },
    { archive_groupchats, true },
    { archive_chat_markers, true },
    { user_prefs_store, mnesia },
    { muc, [
      { host, "muclight.@HOST@" },
      { async_writer, false }
    ] }
  ] },

  { mod_muc_light, [
      { host, "muclight.@HOST@" },
      { backend, mnesia },
      { equal_occupants, true },
      { all_can_configure, true },
      { all_can_invite, true },
      { rooms_in_rosters, true },
      { rooms_per_page, infinity },
      { rooms_in_rosters, true }
  ] }
```

Please advise. Many thanks in advance.

**Comment by fenek** [comment]
Hi @theanhoo 

How do you query for message archive for MUC Light?

**Comment by theanhoo** [comment]
Hi @fenek 

It was due to timeout. Sorry for missing this earlier.

Could you advise me on how to resolve the timeout issue?

Many thanks in advance.

```
SENT (39): <iq id='SBzql-1659' type='set'><query xmlns='urn:xmpp:mam:1' queryid='6e03e8cc-2bc8-4611-9148-3c5e74407825'><x xmlns='jabber:x:data' type='submit'><field var='FORM_TYPE' type='hidden'><value>urn:xmpp:mam:1</value></field><field var='with'><value>ml-68027778-1c6b-44e4-912b-c7bbd0143602@muclight.example.com</value></field></x><set xmlns='http://jabber.org/protocol/rsm'><after>f9bc8bcd-2c56-4493-adb2-d6c3fd474a42</after><max>5</max></set></query></iq>
org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 30000ms (~30s). Waited for response using: IQReplyFilter: iqAndIdFilter (AndFilter: (OrFilter: (IQTypeFilter: type=error, IQTypeFilter: type=result), StanzaIdFilter: id=SBzql-1659)), : fromFilter (OrFilter: (FromMatchesFilter (full): null, FromMatchesFilter (ignoreResourcepart): user1@example.com, FromMatchesFilter (full): example.com)).
    at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:265)
    at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:219)
    at org.jivesoftware.smackx.mam.MamManager.queryArchivePage(MamManager.java:915)
    at org.jivesoftware.smackx.mam.MamManager.queryArchive(MamManager.java:898)
    at org.jivesoftware.smackx.mam.MamManager.queryArchive(MamManager.java:653)
    at com.example.chat.muc.Group.getMUCLightMessages(Group.java:634)
    at com.example.chat.connection.Connection.executeMUCRoomFunctions(Connection.java:2191)
    at com.example.chat.connection.Connection.run(Connection.java:552)
    at com.example.chat.connection.Connection$6.run(Connection.java:601)
```

**Comment by fenek** [comment]
Do you see any errors on server side in logs when you send this query and observe a timeout?

**Comment by theanhoo** [comment]
Hello, @fenek 

I suspect this is the error. Any advice?
```
11:24:56.842 [warning] event=process_iq_error,reason={badarg,[{erlang,binary_to_integer,[<<"f9bc8bcd-2c56-4493-adb2-d6c3fd474a42">>,32],[]},{mod_mam_utils,external_binary_to_mess_id,1,[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mod_mam_utils.erl"},{line,238}]},{mam_iq,fix_rsm,1,[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mam_iq.erl"},{line,110}]},{mam_iq,common_lookup_params,3,[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mam_iq.erl"},{line,212}]},{mam_iq,form_to_lookup_params,4,[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mam_iq.erl"},{line,179}]},{mod_mam,handle_set_message_form,3,[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mod_mam.erl"},{line,418}]},{mod_mam,process_mam_iq,4,[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mod_mam.erl"},{line,247}]},{gen_iq_handler,process_iq,7,[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/gen_iq_handler.erl"},{line,143}]}]},stack_trace=[{erlang,binary_to_integer,[<<"f9bc8bcd-2c56-4493-adb2-d6c3fd474a42">>,32],[]},{mod_mam_utils,external_binary_to_mess_id,1,[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mod_mam_utils.erl"},{line,238}]},{mam_iq,fix_rsm,1,[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mam_iq.erl"},{line,110}]},{mam_iq,common_lookup_params,3,[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mam_iq.erl"},{line,212}]},{mam_iq,form_to_lookup_params,4,[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mam_iq.erl"},{line,179}]},{mod_mam,handle_set_message_form,3,[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mod_mam.erl"},{line,418}]},{mod_mam,process_mam_iq,4,[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mod_mam.erl"},{line,247}]},{gen_iq_handler,process_iq,7,[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/gen_iq_handler.erl"},{line,143}]}]
```

The same content, but with linebreaks:
```
11:24:56.842 [warning] event=process_iq_error,reason=
{badarg,[{erlang,binary_to_integer,[<<"f9bc8bcd-2c56-4493-adb2-d6c3fd474a42">>,32],[]},
{mod_mam_utils,external_binary_to_mess_id,1,
[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mod_mam_utils.erl"},
{line,238}]},{mam_iq,fix_rsm,1,
[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mam_iq.erl"},
{line,110}]},{mam_iq,common_lookup_params,3,
[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mam_iq.erl"},
{line,212}]},{mam_iq,form_to_lookup_params,4,
[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mam_iq.erl"},
{line,179}]},{mod_mam,handle_set_message_form,3,
[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mod_mam.erl"},
{line,418}]},{mod_mam,process_mam_iq,4,
[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mod_mam.erl"},
{line,247}]},{gen_iq_handler,process_iq,7,
[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/gen_iq_handler.erl"},
{line,143}]}]},stack_trace=[{erlang,binary_to_integer,
[<<"f9bc8bcd-2c56-4493-adb2-d6c3fd474a42">>,32],[]},{mod_mam_utils,external_binary_to_mess_id,1,
[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mod_mam_utils.erl"},
{line,238}]},{mam_iq,fix_rsm,1,
[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mam_iq.erl"},
{line,110}]},{mam_iq,common_lookup_params,3,
[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mam_iq.erl"},
{line,212}]},{mam_iq,form_to_lookup_params,4,
[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mam_iq.erl"},
{line,179}]},{mod_mam,handle_set_message_form,3,
[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mod_mam.erl"},{line,418}]},
{mod_mam,process_mam_iq,4,
[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/mam/mod_mam.erl"},
{line,247}]},{gen_iq_handler,process_iq,7,
[{file,"/home/yth/MongooseIM-master/_build/prod/lib/mongooseim/src/gen_iq_handler.erl"},{line,143}]}]
```

**Comment by fenek** [comment]
Yes, it clarifies a lot. :) You are trying to paginate with stanza ID, correct? When paginating through message archive, you need to use "MAM ID". It's attached to every received message as top subelement (sibling of e.g. `<body/>`). Look for `<stanza-id/>` element.

**Comment by theanhoo** [comment]
@fenek 

Thank you very much. I've resolved the issue based on what you said.

Again, thank you very much.

Beer and dinner on me if you are ever in Kuala Lumpur, Malaysia.

**Comment by theanhoo** [comment]
@fenek 

When I receive a MUC Light message when I'm online, the incoming message has two `<stanza-id/>`:
```
BY=room@muclight.example.com, STANZA-ID=B14MO23V5DG1
BY=sender@example.com, STANZA-ID=B14MO2403AO1
```

When I'm querying for MAM, the incoming message has only one `<stanza-id/>`:
```
BY=room@muclight.example.com, STANZA-ID=B14MO23V5DG1
```

My questions are:
1. What JID should I use for subsequent queries, and
2. What stanza ID should I use in `<after/>`?

I've tried using `room@muclight.example.com` and its stanza ID but I kept getting **error 404** from the server.

Many thanks in advance.

**Comment by fenek** [comment]
Two `<stanza-id/>` are caused by `{archive_groupchats, true}` option. It means that a message is effectively stored in two archives: a room archive and user's archive. It means that e.g. if a room is deleted (and its archive), the user may still retrieve its messages from a personal archive.

You should use "sender" stanza ID while querying personal archive and "room" stanza ID when querying room's archive.

Stanza returned in query result will only have the ID of the archive that stored it.

**Comment by theanhoo** [comment]
@fenek 

Are you saying I should query using only the "room" stanza ID, without the "room" ID `room@muclight.example.com`?

Many thanks in advance.

**Comment by theanhoo** [comment]
@fenek 

I can't seem to query successfully using `<after/>`. I kept getting **404 item-not-found** every time I tried it with `<after/>`. 

Please note the query was successful if I didn't set `<after/>`.

Query without "with":
```
<iq id="CgMed-47" type="set">
  <query xmlns="urn:xmpp:mam:1" queryid="447ee216-8066-43b1-84d6-2eccb5f3883b">
    <x xmlns="jabber:x:data" type="submit">
      <field var="FORM_TYPE" type="hidden">
        <value>urn:xmpp:mam:1</value>
      </field>
    </x>
    <set xmlns="http://jabber.org/protocol/rsm">
      <after>B1604QG1T401</after>
      <max>5</max>
    </set>
  </query>
</iq>

<iq from="user1@example.com" to="user1@example.com/mobile" id="CgMed-47" type="error">
  <error code="404" type="cancel">
    <item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
  </error>
</iq>
```

Query with "with" set to room ID:
```
<iq id="fQu2t-52" type="set">
  <query xmlns="urn:xmpp:mam:1" queryid="0c3168c5-6243-478d-a43d-debf9a0d69b1">
    <x xmlns="jabber:x:data" type="submit">
      <field var="FORM_TYPE" type="hidden">
        <value>urn:xmpp:mam:1</value>
      </field>
      <field var="with">
        <value>room@muclight.example.com</value>
      </field>
    </x>
    <set xmlns="http://jabber.org/protocol/rsm">
      <after>B1604QG1T401</after>
      <max>5</max>
    </set>
  </query>
</iq>

<iq from="user1@example.com" to="user1@example.com/mobile" id="fQu2t-52" type="error">
  <error code="404" type="cancel">
    <item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
  </error>
</iq>
```

Please advise.

Many thanks in advance.

**Comment by fenek** [comment]
I'm sorry for a delay. I guess that most probably you have resolved your issue already but if it's not the case, here's a hint:
It seems that you have configured `mod_mam` only for MUC, so you need to send MAM request to the room bare JID (and currently you are not setting `to` attribute at all`).
